// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function OpenImageFile():Promise<string>;

export function OpenMusicFiles():Promise<Array<main.Metadata>>;

export function SaveMetadata(arg1:Array<main.Metadata>):Promise<boolean>;
