// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenImageFile() {
  return window['go']['main']['App']['OpenImageFile']();
}

export function OpenMusicFiles() {
  return window['go']['main']['App']['OpenMusicFiles']();
}

export function SaveMetadata(arg1) {
  return window['go']['main']['App']['SaveMetadata'](arg1);
}
